### ISSUE TITLE
Got RuntimeError while running the sample code. (RuntimeError: expected device cpu but got device cuda:0)

### ISSUE THREAD

**Issue by longerHost** [romulus0914/NASBench-PyTorch#3] opened 2022-08-16 07:47 UTC
Got errors while I run `python main.py`, the program crashed and then threw the error `RuntimeError: expected device cpu but got device cuda:0`. The crash happened at [here](https://github.com/romulus0914/NASBench-PyTorch/blob/master/nasbench_pytorch/trainer.py#L71).

Thanks for your time.

**Comment by longerHost** [comment] 2022-08-17 15:01
If you want to run `main.py` on GPU, there are several tensors were not moved to GPU, the calculation of tensors on different devices caused this issue. I was able to make it work by adding `to("cuda")` at [train_loss](https://github.com/romulus0914/NASBench-PyTorch/blob/master/nasbench_pytorch/trainer.py#L62), [correct](https://github.com/romulus0914/NASBench-PyTorch/blob/master/nasbench_pytorch/trainer.py#L63) and [vertex_input](https://github.com/romulus0914/NASBench-PyTorch/blob/master/nasbench_pytorch/model/model.py#L150) respectively.

The errors were reproduced on my local PC with a NVIDIA 3060 card and an AWS `p2.xlarge` instance with `Deep Learning AMI GPU PyTorch 1.12.0 (Ubuntu 20.04) 20220803` AMI. So I might assume that some users would encounter similar issues while training on GPU.

**Comment by gabikadlecova** [comment] 2022-09-15 09:18
Apologies for the late reply - I had "Watch" turned off by mistake, so I didn't get the notification.

I uploaded a fix that should work for both cuda & cpu training. Thank you for highlighting the places that caused the error. I verified the fix on a cuda machine and I will close the issue; if the problem isn't fixed for you, I will reopen it.

**Closed as completed by gabikadlecova** 2022-09-15 09:18 UTC

**Comment by longerHost** [comment] 2022-10-05 09:01
Thanks for the update, it works well now.
